/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/Login/index'
import { Route as AuthRegisterIndexRouteImport } from './routes/auth/register/index'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/auth/reset-password/index'
import { Route as DashboardExploreIndexRouteImport } from './routes/dashboard/Explore/index'
import { Route as DashboardHomeIndexRouteImport } from './routes/dashboard/Home/index'
import { Route as DashboardMessagesIndexRouteImport } from './routes/dashboard/Messages/index'
import { Route as DashboardNotificationsIndexRouteImport } from './routes/dashboard/Notifications/index'
import { Route as DashboardProfileIndexRouteImport } from './routes/dashboard/Profile/index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/Settings/index'
import { Route as DashboardBuildSessionIdRouteImport } from './routes/dashboard/build/$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/Login/',
  path: '/Login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardExploreIndexRoute = DashboardExploreIndexRouteImport.update({
  id: '/Explore/',
  path: '/Explore/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardHomeIndexRoute = DashboardHomeIndexRouteImport.update({
  id: '/Home/',
  path: '/Home/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMessagesIndexRoute = DashboardMessagesIndexRouteImport.update({
  id: '/Messages/',
  path: '/Messages/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardNotificationsIndexRoute =
  DashboardNotificationsIndexRouteImport.update({
    id: '/Notifications/',
    path: '/Notifications/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProfileIndexRoute = DashboardProfileIndexRouteImport.update({
  id: '/Profile/',
  path: '/Profile/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/Settings/',
  path: '/Settings/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBuildSessionIdRoute = DashboardBuildSessionIdRouteImport.update({
  id: '/build/$sessionId',
  path: '/build/$sessionId',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/build/$sessionId': typeof DashboardBuildSessionIdRoute
  '/auth/Login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/dashboard/Explore/': typeof DashboardExploreIndexRoute
  '/dashboard/Home/': typeof DashboardHomeIndexRoute
  '/dashboard/Messages/': typeof DashboardMessagesIndexRoute
  '/dashboard/Notifications/': typeof DashboardNotificationsIndexRoute
  '/dashboard/Profile/': typeof DashboardProfileIndexRoute
  '/dashboard/Settings/': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/build/$sessionId': typeof DashboardBuildSessionIdRoute
  '/auth/Login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
  '/dashboard/Explore': typeof DashboardExploreIndexRoute
  '/dashboard/Home': typeof DashboardHomeIndexRoute
  '/dashboard/Messages': typeof DashboardMessagesIndexRoute
  '/dashboard/Notifications': typeof DashboardNotificationsIndexRoute
  '/dashboard/Profile': typeof DashboardProfileIndexRoute
  '/dashboard/Settings': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/build/$sessionId': typeof DashboardBuildSessionIdRoute
  '/auth/Login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/dashboard/Explore/': typeof DashboardExploreIndexRoute
  '/dashboard/Home/': typeof DashboardHomeIndexRoute
  '/dashboard/Messages/': typeof DashboardMessagesIndexRoute
  '/dashboard/Notifications/': typeof DashboardNotificationsIndexRoute
  '/dashboard/Profile/': typeof DashboardProfileIndexRoute
  '/dashboard/Settings/': typeof DashboardSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/build/$sessionId'
    | '/auth/Login/'
    | '/auth/register/'
    | '/auth/reset-password/'
    | '/dashboard/Explore/'
    | '/dashboard/Home/'
    | '/dashboard/Messages/'
    | '/dashboard/Notifications/'
    | '/dashboard/Profile/'
    | '/dashboard/Settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/build/$sessionId'
    | '/auth/Login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/dashboard/Explore'
    | '/dashboard/Home'
    | '/dashboard/Messages'
    | '/dashboard/Notifications'
    | '/dashboard/Profile'
    | '/dashboard/Settings'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/build/$sessionId'
    | '/auth/Login/'
    | '/auth/register/'
    | '/auth/reset-password/'
    | '/dashboard/Explore/'
    | '/dashboard/Home/'
    | '/dashboard/Messages/'
    | '/dashboard/Notifications/'
    | '/dashboard/Profile/'
    | '/dashboard/Settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/Login/': {
      id: '/auth/Login/'
      path: '/Login'
      fullPath: '/auth/Login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/register'
      fullPath: '/auth/register/'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/reset-password/': {
      id: '/auth/reset-password/'
      path: '/reset-password'
      fullPath: '/auth/reset-password/'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/dashboard/Explore/': {
      id: '/dashboard/Explore/'
      path: '/Explore'
      fullPath: '/dashboard/Explore/'
      preLoaderRoute: typeof DashboardExploreIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/Home/': {
      id: '/dashboard/Home/'
      path: '/Home'
      fullPath: '/dashboard/Home/'
      preLoaderRoute: typeof DashboardHomeIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/Messages/': {
      id: '/dashboard/Messages/'
      path: '/Messages'
      fullPath: '/dashboard/Messages/'
      preLoaderRoute: typeof DashboardMessagesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/Notifications/': {
      id: '/dashboard/Notifications/'
      path: '/Notifications'
      fullPath: '/dashboard/Notifications/'
      preLoaderRoute: typeof DashboardNotificationsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/Profile/': {
      id: '/dashboard/Profile/'
      path: '/Profile'
      fullPath: '/dashboard/Profile/'
      preLoaderRoute: typeof DashboardProfileIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/Settings/': {
      id: '/dashboard/Settings/'
      path: '/Settings'
      fullPath: '/dashboard/Settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/build/$sessionId': {
      id: '/dashboard/build/$sessionId'
      path: '/build/$sessionId'
      fullPath: '/dashboard/build/$sessionId'
      preLoaderRoute: typeof DashboardBuildSessionIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBuildSessionIdRoute: typeof DashboardBuildSessionIdRoute
  DashboardExploreIndexRoute: typeof DashboardExploreIndexRoute
  DashboardHomeIndexRoute: typeof DashboardHomeIndexRoute
  DashboardMessagesIndexRoute: typeof DashboardMessagesIndexRoute
  DashboardNotificationsIndexRoute: typeof DashboardNotificationsIndexRoute
  DashboardProfileIndexRoute: typeof DashboardProfileIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBuildSessionIdRoute: DashboardBuildSessionIdRoute,
  DashboardExploreIndexRoute: DashboardExploreIndexRoute,
  DashboardHomeIndexRoute: DashboardHomeIndexRoute,
  DashboardMessagesIndexRoute: DashboardMessagesIndexRoute,
  DashboardNotificationsIndexRoute: DashboardNotificationsIndexRoute,
  DashboardProfileIndexRoute: DashboardProfileIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
